'use client'
import { use, useEffect, useMemo, useState } from 'react'
import { supabase } from '@/lib/supabase'
import type { Category, Location, PlacedOrder, Product } from '@/lib/types'
type CartItem={product:Product;quantity:number}
const rub=(n:number)=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(n)
export default function Menu({params}:{params:Promise<{locationSlug:string}>}){
 const {locationSlug}=use(params),[location,setLocation]=useState<Location|null>(null),[categories,setCategories]=useState<Category[]>([]),[products,setProducts]=useState<Product[]>([]),[cart,setCart]=useState<CartItem[]>([]),[cartOpen,setCartOpen]=useState(false),[notes,setNotes]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[placing,setPlacing]=useState(false),[placed,setPlaced]=useState<PlacedOrder|null>(null),[status,setStatus]=useState<string|null>(null),[error,setError]=useState<string|null>(null)
 useEffect(()=>{(async()=>{const {data:loc,error:e}=await supabase.from('locations').select('*').eq('slug',locationSlug).eq('active',true).single();if(e||!loc){setError('Точка не найдена');return}setLocation(loc);const [c,p]=await Promise.all([supabase.from('categories').select('*').eq('location_id',loc.id).eq('active',true).order('sort_order'),supabase.from('products').select('*').eq('location_id',loc.id).eq('available',true).order('sort_order')]);setCategories(c.data||[]);setProducts(p.data||[])})()},[locationSlug])
 useEffect(()=>{if(!placed)return;const tick=async()=>{const {data}=await supabase.rpc('get_order_status',{p_token:placed.public_token});if(data?.status)setStatus(data.status)};tick();const id=setInterval(tick,5000);return()=>clearInterval(id)},[placed])
 const count=cart.reduce((s,x)=>s+x.quantity,0),total=cart.reduce((s,x)=>s+x.product.price*x.quantity,0)
 const grouped=useMemo(()=>categories.map(c=>({c,items:products.filter(p=>p.category_id===c.id)})).filter(x=>x.items.length),[categories,products])
 function add(p:Product){setCart(v=>{const i=v.findIndex(x=>x.product.id===p.id);return i<0?[...v,{product:p,quantity:1}]:v.map((x,n)=>n===i?{...x,quantity:x.quantity+1}:x)})}
 function dec(i:number){setCart(v=>v.map((x,n)=>n===i?{...x,quantity:x.quantity-1}:x).filter(x=>x.quantity>0))}
 async function place(){if(!location||!cart.length)return;setPlacing(true);setError(null);const p_items=cart.map(x=>({product_id:x.product.id,quantity:x.quantity,modifier_ids:[]}));const {data,error:e}=await supabase.functions.invoke('place-order',{body:{location_id:location.id,items:p_items,customer_name:name||null,customer_phone:phone||null,notes:notes||null}});setPlacing(false);if(e||data?.error){setError('Не удалось оформить заказ. Попробуйте ещё раз.');return}if(!data?.order_id||!data?.public_token){setError('Заказ создан некорректно. Обратитесь к сотруднику.');return}setPlaced(data as PlacedOrder);setStatus(data.status);setCart([]);setCartOpen(false)}
 if(error&&!location)return <main className="min-h-screen grid place-items-center p-6"><p>{error}</p></main>
 if(!location)return <main className="min-h-screen grid place-items-center p-6"><p>Загружаем меню…</p></main>
 if(placed){const labels:Record<string,string>={pending:'Ожидает подтверждения',accepted:'Заказ принят',preparing:'Готовится',ready:'Можно забирать',completed:'Выдан',rejected:'Заказ отклонён',cancelled:'Отменён'};return <main className="min-h-screen bg-neutral-50 p-6 grid place-items-center"><section className="w-full max-w-md bg-white rounded-3xl p-7 shadow-sm text-center"><div className="text-sm text-neutral-500">Шаваллея</div><h1 className="text-4xl font-black mt-2">№ {placed.order_number}</h1><p className="mt-6 text-xl font-bold">{labels[status||placed.status]||status}</p><p className="text-neutral-500 mt-2">Покажите номер при получении заказа.</p><p className="font-bold mt-5">{rub(placed.total)}</p><button className="mt-8 w-full rounded-2xl border py-3 font-semibold" onClick={()=>setPlaced(null)}>Вернуться в меню</button></section></main>}
 return <main className="min-h-screen bg-neutral-50 pb-28"><header className="sticky top-0 z-20 bg-white/95 backdrop-blur border-b"><div className="max-w-xl mx-auto p-4"><h1 className="text-2xl font-black">Шаваллея</h1><p className="text-sm text-neutral-500">{location.address}</p></div></header><div className="max-w-xl mx-auto p-4">
 {grouped.length===0&&<div className="bg-white rounded-3xl p-8 text-center"><h2 className="font-bold text-lg">Меню готовится</h2><p className="text-neutral-500 mt-2">Скоро здесь появятся позиции.</p></div>}
 {grouped.map(({c,items})=><section key={c.id} className="mb-8"><h2 className="text-xl font-black mb-3">{c.name}</h2><div className="space-y-3">{items.map(p=><button key={p.id} onClick={()=>add(p)} className="w-full text-left bg-white rounded-2xl p-4 shadow-sm flex gap-4 items-center"><div className="w-20 h-20 rounded-xl bg-neutral-100 overflow-hidden shrink-0">{p.image_url?<img src={p.image_url} alt="" className="w-full h-full object-cover"/>:<div className="w-full h-full grid place-items-center text-2xl">🌯</div>}</div><div className="flex-1"><div className="font-bold">{p.name}</div>{p.description&&<div className="text-sm text-neutral-500 mt-1">{p.description}</div>}<div className="font-black mt-2">{rub(p.price)}</div></div><span className="text-2xl">＋</span></button>)}</div></section>)}</div>
 {count>0&&<div className="fixed bottom-4 left-4 right-4 z-30"><button onClick={()=>setCartOpen(true)} className="max-w-xl mx-auto w-full bg-black text-white rounded-2xl px-5 py-4 font-bold flex justify-between shadow-xl"><span>Корзина · {count}</span><span>{rub(total)}</span></button></div>}
 {cartOpen&&<div className="fixed inset-0 z-50 bg-black/40 flex items-end"><div className="bg-white w-full rounded-t-3xl p-6 max-h-[90vh] overflow-auto"><div className="flex justify-between"><h2 className="text-2xl font-black">Ваш заказ</h2><button onClick={()=>setCartOpen(false)}>✕</button></div><div className="mt-5 space-y-4">{cart.map((x,i)=><div key={x.product.id} className="flex justify-between gap-3"><div><div className="font-bold">{x.product.name}</div><div>{rub(x.product.price)}</div></div><div className="flex items-center gap-3"><button onClick={()=>dec(i)} className="border rounded-full w-8 h-8">−</button><b>{x.quantity}</b><button onClick={()=>add(x.product)} className="border rounded-full w-8 h-8">+</button></div></div>)}</div><div className="grid grid-cols-2 gap-3 mt-6"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Имя (необязательно)" className="border rounded-xl p-3"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Телефон (необязательно)" className="border rounded-xl p-3"/></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Комментарий к заказу" className="w-full border rounded-xl p-3 mt-3"/>{error&&<p className="text-red-600 text-sm mt-3">{error}</p>}<div className="flex justify-between text-xl font-black mt-5"><span>Итого</span><span>{rub(total)}</span></div><button disabled={placing||!cart.length} onClick={place} className="w-full bg-black text-white rounded-2xl py-4 font-bold mt-5 disabled:opacity-50">{placing?'Оформляем…':'Заказать · оплата при получении'}</button></div></div>}
 </main>
}